### ISSUE TITLE
多余文本

### ISSUE THREAD

**Issue by LEAVING-7** [xiaoweiChen/CXX20-Get-Details#3]
https://github.com/xiaoweiChen/CXX20-Get-Details/blob/8e389dcef1b534bbf96a3da922b024ad65ec02a5/content/3/chapter4/1.tex#L718
“吃点饭 VVVVVVVVVV”

**Comment by xiaoweiChen** [comment]
😯，估计是我家猫干的

**Comment by xiaoweiChen** [comment]
fixed on 58fa9a1d.

感谢勘误！
